### PR TITLE
Update tar command to remove absolute paths from the archive

### PR DESCRIPTION
**Pull request by deepakduggirala**
**Description**

Current command create tar files with full path of the directory. Ex:

running the command `tar cf /N/scratch/bioloop/foo.tar --sparse /N/project/bioloop/raw_data/test_dataset` produces a foo.tar when extracted

`tar xf foo.tar` produces the below hierarchy in the directory where it was extracted.
- N/
  - project/
    - bioloop/
      - raw_data/
        - test_dataset/
          - ... files/dirs of the dataset

`tar cf /N/scratch/bioloop/foo.tar --sparse -C /N/project/bioloop/raw_data/test_dataset .` removes absolute paths from the archive and when extracted just produces:

`tar xf foo.tar

- foo/
  - ... files/dirs of the dataset

### CODE REVIEW

**Comment by deepakduggirala** [comment]
Need to validate this is dev environment

**Review by charlesbrandt — APPROVED** [review]
Makes sense. Thanks!

**Comment by ri-pandey** [comment]
Tested in dev env.

Tested with Data Product sub-fsm54jc.

```
[scadev@colo25 staged]$ cd data_products/
[scadev@colo25 data_products]$ cd 3a1e0f21c1770ef5dd6bd10f92aa35b4
[scadev@colo25 3a1e0f21c1770ef5dd6bd10f92aa35b4]$ ls
sub-fsm70qy
```

The extracted tar file's root path is the dataset's containing directory.

**Comment by deepakduggirala** [comment]
@ri-pandey No, I have not.

**Comment by ri-pandey** [comment]
@deepakduggirala I tested the downloaded bundle, and unextracting it has the correct paths.

Fwiw, I used the 'Archive Utility' app on Mac to extract the bundle. This resulted in the root directory of the extracted contents to have the same name as the name of the bundle.

Screenshot 2024-09-06 at 12 04 55 PM

Running `tar xvf a49d5175a091376bf5785768e6386e0e` however results in the the sub-directories inside the dataset to be extracted to the same directory where the tar is located.

Screenshot 2024-09-06 at 12 07 24 PM

I used dataset 35 (sub-fsm84zy_copy) in the bioloop dev env to test this.

**Comment by deepakduggirala** [comment]
@ri-pandey Looks good. Feel free to merge when you're ready.

**Pull request merged**
